SCR_ArsenalItemListConfig {
 m_aArsenalItems {
  SCR_ArsenalItemStandalone "{69D6813F43C1DE2C}" {
   m_ItemResourceName "{260827F90690140A}Prefabs/Items/Medicine/Tourniquet_01/Tourniquet_US_01_base.et"
  }
  SCR_ArsenalItemStandalone "{69D6813F435A4EC9}" {
   m_ItemResourceName "{0D9A5DCF89AE7AA9}Prefabs/Items/Medicine/MorphineInjection_01/MorphineInjection_01.et"
  }
  SCR_ArsenalItemStandalone "{69D6813F40DD44B7}" {
   m_ItemResourceName "{A81F501D3EF6F38E}Prefabs/Items/Medicine/FieldDressing_01/FieldDressing_US_01.et"
  }
  SCR_ArsenalItemStandalone "{69D6813CAA932032}" {
   m_ItemResourceName "{5C5C6EE05EE2FF1A}Prefabs/Items/Equipment/Backpacks/Backpack_ALICE_Medium_assembled.et"
  }
  SCR_ArsenalItemStandalone "{69D6813CAA51E6B8}" {
   m_ItemResourceName "{4805E67E2AE30F8D}Prefabs/Items/Equipment/Backpacks/Backpack_Medical_M5.et"
  }
 }
}