SCR_ArsenalItemListConfig {
 m_aArsenalItems {
  SCR_ArsenalItemStandalone "{69B4BD6980E9398C}" {
   m_ItemResourceName "{C0F7DD85A86B2900}Prefabs/Weapons/Handguns/PM/Handgun_PM.et"
  }
  SCR_ArsenalItemStandalone "{69B4BD69E41EBE42}" {
   m_ItemResourceName "{1353C6EAD1DCFE43}Prefabs/Weapons/Handguns/M9/Handgun_M9.et"
  }
  SCR_ArsenalItemStandalone "{69B4BD69ED7FE434}" {
   m_ItemResourceName "{843D9B182BCD2765}Prefabs/Weapons/Magazines/NSV/Box_127x108_NSV_50rnd_4AP_1APIT.et"
  }
  SCR_ArsenalItemStandalone "{69D62871B281E972}" {
   m_SellValue 500
   m_ItemResourceName "{EAE9A298979C4721}Prefabs/Weapons/Rifles/AK74/Rifle_AK74N_base.et"
  }
  SCR_ArsenalItemStandalone "{69D62871F4F36F90}" {
   m_SellValue 50
   m_ItemResourceName "{3B96FAC169E27037}Prefabs/Weapons/Attachments/Muzzle/Suppressor_PBS4/Suppressor_PBS4.et"
  }
  SCR_ArsenalItemStandalone "{69CF0598CF309403}" {
   m_SellValue 200
   m_ItemResourceName "{43497A18DD888667}Prefabs/Weapons/Rifles/AK74/Rifle_AK74_base.et"
  }
  SCR_ArsenalItemStandalone "{69D62871FF6FF7AF}" {
   m_SellValue 30
   m_ItemResourceName "{1ABABE3551512B0A}Prefabs/Weapons/Attachments/Underbarrel/UGL_GP25.et"
  }
  SCR_ArsenalItemStandalone "{69D67C5953DBEE8A}" {
   m_ItemResourceName "{8BA0D0DE316D1B44}Prefabs/Weapons/Rifles/AKS74U/Rifle_AKS74U_base.et"
  }
 }
}